export enum QueryKey {
  FETCH_CATEGORIES = 'FETCH_CATEGORIES',
  FETCH_MY_INTERESTS = 'FETCH_MY_INTERESTS',
  FETCH_MY_PUBLISHERS = 'FETCH_MY_PUBLISHERS',
  FETCH_MY_FRIENDS = 'FETCH_MY_FRIENDS',
  FETCH_PUBLISHER = 'FETCH_PUBLISHER',
}
