export enum QueryKey {
  FETCH_CATEGORIES = 'FETCH_CATEGORIES',
  FETCH_MY_PROFILE_STATS = 'FETCH_MY_PROFILE_STATS',
  FETCH_MY_INTERESTS = 'FETCH_MY_INTERESTS',
  FETCH_MY_PUBLISHERS = 'FETCH_MY_PUBLISHERS',
  FETCH_MY_FRIENDS = 'FETCH_MY_FRIENDS',
  FETCH_MY_PENDING = 'FETCH_MY_PENDING',
  FETCH_PUBLISHER = 'FETCH_PUBLISHER',
  FETCH_CONSUMER = 'FETCH_CONSUMER',
  FETCH_FOLLOWERS_OF = 'FETCH_FOLLOWERS_OF',
  FETCH_PUBLISHERS_OF = 'FETCH_PUBLISHERS_OF',
  FETCH_FRIENDS_OF = 'FETCH_FRIENDS_OF',
}
